insert into "person" (name, surname, title, photo) values ('Martin', 'Nitram', 'Ing', 'photo');
insert into "person" (name, surname, photo) values ('Peter', 'Retep', 'photo');
insert into "person" (name, surname, photo) values ('Zuzana', 'Anazova', 'photo');
insert into "person" (name, surname, photo) values ('Jan', 'Naj', 'photo');
insert into "person" (name, surname, photo) values ('Zuzana', 'Kratka', 'photo');
insert into "person" (name, surname, photo) values ('Martin', 'Kratky', 'photo');
insert into "person" (name, surname, photo) values ('Jan', 'Anaz', 'photo');
insert into "person" (name, surname, title, photo) values ('Peter', 'Rataj', 'Ing', 'photo');
insert into "person" (name, surname, title, photo) values ('Jan', 'Jatar', 'Mgr', 'photo');
insert into "person" (name, surname, photo) values ('Frantisek', 'Horky', 'photo');
insert into "person" (name, surname, photo) values ('Frantisek', 'Novak', 'photo');
insert into "person" (name, surname, photo) values ('Peter', 'Kovac', 'photo');
insert into "person" (name, surname, photo) values ('Ema', 'Kovacova', 'photo');
insert into "person" (name, surname, photo) values ('Andrea', 'Rendova', 'photo');
insert into "person" (name, surname, photo) values ('Peter', 'Bystri', 'photo');
insert into "person" (name, surname, photo) values ('Andrea', 'Novakova', 'photo');
insert into "person" (name, surname, photo) values ('Martin', 'Garai', 'photo');
insert into "person" (name, surname, photo) values ('Zuzana', 'Balonova', 'photo');
insert into "person" (name, surname, photo) values ('Martin', 'Balon', 'photo');
insert into "person" (name, surname, photo) values ('Andrea', 'Vilemova', 'photo');
insert into "person" (name, surname, photo) values ('Daniela', 'Vilemova', 'photo');
insert into "person" (name, surname, photo) values ('Jan', 'Zatko', 'photo');
insert into "person" (name, surname, photo) values ('Daniela', 'Adamcova', 'photo');
insert into "person" (name, surname, photo) values ('Erik', 'Ban', 'photo');
insert into "person" (name, surname, photo) values ('Daniela', 'Cibikova', 'photo');
insert into "person" (name, surname, photo) values ('Jan', 'Danek', 'photo');
insert into "person" (name, surname, photo) values ('Martin', 'Fabian', 'photo');
insert into "person" (name, surname, photo) values ('Erik', 'Fabian', 'photo');
insert into "person" (name, surname, photo) values ('Frantisek', 'Mokry', 'photo');
insert into "person" (name, surname, title, photo) values ('Ema', 'Mokra', 'Mgr', 'photo');
insert into "person" (name, surname, title, photo) values ('Andrea', 'Gallova', 'MUDr', 'photo');
insert into "person" (name, surname, title, photo) values ('Zuzana', 'Havranova', 'MUDr', 'photo');
insert into "person" (name, surname, title, photo) values ('Samo', 'Chalupka', 'MUDr', 'photo');
insert into "person" (name, surname, title, photo) values ('Ivan', 'Jakab', 'MUDr', 'photo');
insert into "person" (name, surname, photo) values ('Ivan', 'Jurek', 'photo');
insert into "person" (name, surname, photo) values ('Peter', 'Klepsatel', 'photo');
insert into "person" (name, surname, title, photo) values ('Ivan', 'Luks', 'MDDr', 'photo');
insert into "person" (name, surname, title, photo) values ('Boris', 'Luks', 'MDDr', 'photo');
insert into "person" (name, surname, photo) values ('Ema', 'Machova', 'photo');
insert into "person" (name, surname, photo) values ('Boris', 'Mak', 'photo');
insert into "person" (name, surname, photo) values ('Frantisek', 'Maslo', 'photo');
insert into "person" (name, surname, photo) values ('Boris', 'Mensik', 'photo');
insert into "person" (name, surname, title, photo) values ('Lubomir', 'Orlik', 'Mgr', 'photo');
insert into "person" (name, surname, photo) values ('Lubomir', 'Pala', 'photo');
insert into "person" (name, surname, photo) values ('Lubomir', 'Rak', 'photo');
insert into "person" (name, surname, photo) values ('Peter', 'Sagan', 'photo');
insert into "person" (name, surname, photo) values ('Filip', 'Trben', 'photo');
insert into "person" (name, surname, photo) values ('Andrea', 'Valentova', 'photo');
insert into "person" (name, surname, title, photo) values ('Filip', 'Weiss', 'MUDr', 'photo');
insert into "person" (name, surname, title, photo) values ('Martin', 'Zajac', 'MUDr', 'photo')